insert 
$tag-class-349 value "OfficeHolder", isa tag-class, id "tag-class-349";
$tag-class-349_name_1683705768 isa name, value "OfficeHolder";
isa entity-has-resource, (entity-target $tag-class-349, entity-value $tag-class-349_name_1683705768);
$tag-class-211 id "tag-class-211", isa tag-class;
isa subclass-of, (superclass $tag-class-211, subclass $tag-class-349);
$tag-class-211 id "tag-class-211", value "Person", isa tag-class;
$tag-class-211_name_-1907849355 isa name, value "Person";
(entity-value $tag-class-211_name_-1907849355, entity-target $tag-class-211), isa entity-has-resource;
$tag-class-239 isa tag-class, id "tag-class-239";
(subclass $tag-class-211, superclass $tag-class-239), isa subclass-of;
$tag-class-239 value "Agent", isa tag-class, id "tag-class-239";
$tag-class-239_name_63197925 isa name, value "Agent";
isa entity-has-resource, (entity-value $tag-class-239_name_63197925, entity-target $tag-class-239);
$tag-class-0 isa tag-class, id "tag-class-0";
(superclass $tag-class-0, subclass $tag-class-239), isa subclass-of;
$tag-class-0 isa tag-class, value "Thing", id "tag-class-0";
$tag-class-0_name_80778446 isa name, value "Thing";
isa entity-has-resource, (entity-value $tag-class-0_name_80778446, entity-target $tag-class-0);
$tag-class-98 value "Monarch", id "tag-class-98", isa tag-class;
$tag-class-98_name_-1394235070 isa name, value "Monarch";
(entity-target $tag-class-98, entity-value $tag-class-98_name_-1394235070), isa entity-has-resource;
$tag-class-211 id "tag-class-211", isa tag-class;
(superclass $tag-class-211, subclass $tag-class-98), isa subclass-of;
$tag-class-336 id "tag-class-336", isa tag-class, value "BritishRoyalty";
$tag-class-336_name_-950275767 isa name, value "BritishRoyalty";
(entity-value $tag-class-336_name_-950275767, entity-target $tag-class-336), isa entity-has-resource;
$tag-class-155 id "tag-class-155", isa tag-class;
(superclass $tag-class-155, subclass $tag-class-336), isa subclass-of;
$tag-class-155 id "tag-class-155", value "Royalty", isa tag-class;
$tag-class-155_name_-1241530452 isa name, value "Royalty";
(entity-target $tag-class-155, entity-value $tag-class-155_name_-1241530452), isa entity-has-resource;
$tag-class-211 id "tag-class-211", isa tag-class;
(superclass $tag-class-211, subclass $tag-class-155), isa subclass-of;
$tag-class-193 value "Saint", id "tag-class-193", isa tag-class;
$tag-class-193_name_79646401 isa name, value "Saint";
(entity-target $tag-class-193, entity-value $tag-class-193_name_79646401), isa entity-has-resource;
$tag-class-109 id "tag-class-109", isa tag-class;
(subclass $tag-class-193, superclass $tag-class-109), isa subclass-of;
$tag-class-109 value "Cleric", id "tag-class-109", isa tag-class;
$tag-class-109_name_2021015184 isa name, value "Cleric";
(entity-value $tag-class-109_name_2021015184, entity-target $tag-class-109), isa entity-has-resource;
$tag-class-211 id "tag-class-211", isa tag-class;
(subclass $tag-class-109, superclass $tag-class-211), isa subclass-of;
$tag-class-82 value "Philosopher", isa tag-class, id "tag-class-82";
$tag-class-82_name_583005333 isa name, value "Philosopher";
(entity-value $tag-class-82_name_583005333, entity-target $tag-class-82), isa entity-has-resource;
$tag-class-211 id "tag-class-211", isa tag-class;
(subclass $tag-class-82, superclass $tag-class-211), isa subclass-of;
$tag-class-88 id "tag-class-88", value "Writer", isa tag-class;
$tag-class-88_name_-1695706989 isa name, value "Writer";
isa entity-has-resource, (entity-value $tag-class-88_name_-1695706989, entity-target $tag-class-88);
$tag-class-250 isa tag-class, id "tag-class-250";
isa subclass-of, (subclass $tag-class-88, superclass $tag-class-250);
$tag-class-250 value "Artist", isa tag-class, id "tag-class-250";
$tag-class-250_name_1969736551 isa name, value "Artist";
(entity-value $tag-class-250_name_1969736551, entity-target $tag-class-250), isa entity-has-resource;
$tag-class-211 id "tag-class-211", isa tag-class;
(subclass $tag-class-250, superclass $tag-class-211), isa subclass-of;
$tag-class-57 id "tag-class-57", value "President", isa tag-class;
$tag-class-57_name_1085406624 isa name, value "President";
(entity-value $tag-class-57_name_1085406624, entity-target $tag-class-57), isa entity-has-resource;
$tag-class-95 isa tag-class, id "tag-class-95";
(subclass $tag-class-57, superclass $tag-class-95), isa subclass-of;
$tag-class-95 value "Politician", isa tag-class, id "tag-class-95";
$tag-class-95_name_-235595292 isa name, value "Politician";
isa entity-has-resource, (entity-value $tag-class-95_name_-235595292, entity-target $tag-class-95);
$tag-class-211 id "tag-class-211", isa tag-class;
(superclass $tag-class-211, subclass $tag-class-95), isa subclass-of;
$tag-class-94 value "SoccerManager", isa tag-class, id "tag-class-94";
$tag-class-94_name_228662756 isa name, value "SoccerManager";
(entity-value $tag-class-94_name_228662756, entity-target $tag-class-94), isa entity-has-resource;
$tag-class-211 id "tag-class-211", isa tag-class;
(subclass $tag-class-94, superclass $tag-class-211), isa subclass-of;
$tag-class-59 value "TennisPlayer", id "tag-class-59", isa tag-class;
$tag-class-59_name_-555310148 isa name, value "TennisPlayer";
(entity-target $tag-class-59, entity-value $tag-class-59_name_-555310148), isa entity-has-resource;
$tag-class-149 id "tag-class-149", isa tag-class;
(subclass $tag-class-59, superclass $tag-class-149), isa subclass-of;
$tag-class-149 id "tag-class-149", isa tag-class, value "Athlete";
$tag-class-149_name_978543007 isa name, value "Athlete";
(entity-target $tag-class-149, entity-value $tag-class-149_name_978543007), isa entity-has-resource;
$tag-class-211 id "tag-class-211", isa tag-class;
(subclass $tag-class-149, superclass $tag-class-211), isa subclass-of;
$tag-class-74 value "SoccerPlayer", isa tag-class, id "tag-class-74";
$tag-class-74_name_-174036534 isa name, value "SoccerPlayer";
(entity-target $tag-class-74, entity-value $tag-class-74_name_-174036534), isa entity-has-resource;
$tag-class-149 id "tag-class-149", isa tag-class;
isa subclass-of, (superclass $tag-class-149, subclass $tag-class-74);
$tag-class-115 value "MusicalArtist", id "tag-class-115", isa tag-class;
$tag-class-115_name_-809044905 isa name, value "MusicalArtist";
(entity-value $tag-class-115_name_-809044905, entity-target $tag-class-115), isa entity-has-resource;
$tag-class-250 isa tag-class, id "tag-class-250";
(superclass $tag-class-250, subclass $tag-class-115), isa subclass-of;
$tag-class-37 value "FormulaOneRacer", id "tag-class-37", isa tag-class;
$tag-class-37_name_-1039521695 isa name, value "FormulaOneRacer";
isa entity-has-resource, (entity-value $tag-class-37_name_-1039521695, entity-target $tag-class-37);
$tag-class-149 id "tag-class-149", isa tag-class;
(superclass $tag-class-149, subclass $tag-class-37), isa subclass-of;
$tag-class-148 id "tag-class-148", value "PrimeMinister", isa tag-class;
$tag-class-148_name_1023115044 isa name, value "PrimeMinister";
(entity-value $tag-class-148_name_1023115044, entity-target $tag-class-148), isa entity-has-resource;
$tag-class-95 isa tag-class, id "tag-class-95";
isa subclass-of, (subclass $tag-class-148, superclass $tag-class-95);
$tag-class-24 value "Cricketer", id "tag-class-24", isa tag-class;
$tag-class-24_name_1906350142 isa name, value "Cricketer";
isa entity-has-resource, (entity-value $tag-class-24_name_1906350142, entity-target $tag-class-24);
$tag-class-149 id "tag-class-149", isa tag-class;
(subclass $tag-class-24, superclass $tag-class-149), isa subclass-of;
$tag-class-191 value "GolfPlayer", isa tag-class, id "tag-class-191";
$tag-class-191_name_2137559555 isa name, value "GolfPlayer";
isa entity-has-resource, (entity-value $tag-class-191_name_2137559555, entity-target $tag-class-191);
$tag-class-149 id "tag-class-149", isa tag-class;
isa subclass-of, (superclass $tag-class-149, subclass $tag-class-191);
$tag-class-96 value "Comedian", isa tag-class, id "tag-class-96";
$tag-class-96_name_-545194858 isa name, value "Comedian";
(entity-value $tag-class-96_name_-545194858, entity-target $tag-class-96), isa entity-has-resource;
$tag-class-250 isa tag-class, id "tag-class-250";
(subclass $tag-class-96, superclass $tag-class-250), isa subclass-of;
$tag-class-319 id "tag-class-319", isa tag-class, value "Cyclist";
$tag-class-319_name_-1402884949 isa name, value "Cyclist";
(entity-target $tag-class-319, entity-value $tag-class-319_name_-1402884949), isa entity-has-resource;
$tag-class-149 id "tag-class-149", isa tag-class;
(subclass $tag-class-319, superclass $tag-class-149), isa subclass-of;
$tag-class-279 id "tag-class-279", value "Scientist", isa tag-class;
$tag-class-279_name_-1555003144 isa name, value "Scientist";
isa entity-has-resource, (entity-target $tag-class-279, entity-value $tag-class-279_name_-1555003144);
$tag-class-211 id "tag-class-211", isa tag-class;
(subclass $tag-class-279, superclass $tag-class-211), isa subclass-of;
$tag-class-226 id "tag-class-226", isa tag-class, value "Judge";
$tag-class-226_name_71925495 isa name, value "Judge";
(entity-value $tag-class-226_name_71925495, entity-target $tag-class-226), isa entity-has-resource;
$tag-class-211 id "tag-class-211", isa tag-class;
(subclass $tag-class-226, superclass $tag-class-211), isa subclass-of;
$tag-class-3 isa tag-class, value "MilitaryPerson", id "tag-class-3";
$tag-class-3_name_-993510686 isa name, value "MilitaryPerson";
isa entity-has-resource, (entity-value $tag-class-3_name_-993510686, entity-target $tag-class-3);
$tag-class-211 id "tag-class-211", isa tag-class;
(subclass $tag-class-3, superclass $tag-class-211), isa subclass-of;
$tag-class-230 isa tag-class, value "MartialArtist", id "tag-class-230";
$tag-class-230_name_-1715221371 isa name, value "MartialArtist";
isa entity-has-resource, (entity-value $tag-class-230_name_-1715221371, entity-target $tag-class-230);
$tag-class-149 id "tag-class-149", isa tag-class;
(subclass $tag-class-230, superclass $tag-class-149), isa subclass-of;
$tag-class-97 id "tag-class-97", value "ComicsCreator", isa tag-class;
$tag-class-97_name_-84535436 isa name, value "ComicsCreator";
isa entity-has-resource, (entity-value $tag-class-97_name_-84535436, entity-target $tag-class-97);
$tag-class-250 isa tag-class, id "tag-class-250";
(subclass $tag-class-97, superclass $tag-class-250), isa subclass-of;
$tag-class-13 id "tag-class-13", isa tag-class, value "IceHockeyPlayer";
$tag-class-13_name_-948618385 isa name, value "IceHockeyPlayer";
(entity-value $tag-class-13_name_-948618385, entity-target $tag-class-13), isa entity-has-resource;
$tag-class-149 id "tag-class-149", isa tag-class;
(superclass $tag-class-149, subclass $tag-class-13), isa subclass-of;
$tag-class-212 id "tag-class-212", isa tag-class, value "Architect";
$tag-class-212_name_337968085 isa name, value "Architect";
(entity-target $tag-class-212, entity-value $tag-class-212_name_337968085), isa entity-has-resource;
$tag-class-211 id "tag-class-211", isa tag-class;
(superclass $tag-class-211, subclass $tag-class-212), isa subclass-of;
$tag-class-330 id "tag-class-330", value "MemberOfParliament", isa tag-class;
$tag-class-330_name_986295090 isa name, value "MemberOfParliament";
isa entity-has-resource, (entity-value $tag-class-330_name_986295090, entity-target $tag-class-330);
$tag-class-95 isa tag-class, id "tag-class-95";
isa subclass-of, (superclass $tag-class-95, subclass $tag-class-330);
$tag-class-43 id "tag-class-43", isa tag-class, value "Wrestler";
$tag-class-43_name_-1896807026 isa name, value "Wrestler";
isa entity-has-resource, (entity-value $tag-class-43_name_-1896807026, entity-target $tag-class-43);
$tag-class-149 id "tag-class-149", isa tag-class;
isa subclass-of, (superclass $tag-class-149, subclass $tag-class-43);
$tag-class-200 id "tag-class-200", isa tag-class, value "Actor";
$tag-class-200_name_63093205 isa name, value "Actor";
isa entity-has-resource, (entity-value $tag-class-200_name_63093205, entity-target $tag-class-200);
$tag-class-250 isa tag-class, id "tag-class-250";
(superclass $tag-class-250, subclass $tag-class-200), isa subclass-of;
$tag-class-354 id "tag-class-354", value "BasketballPlayer", isa tag-class;
$tag-class-354_name_1084870694 isa name, value "BasketballPlayer";
(entity-target $tag-class-354, entity-value $tag-class-354_name_1084870694), isa entity-has-resource;
$tag-class-149 id "tag-class-149", isa tag-class;
(superclass $tag-class-149, subclass $tag-class-354), isa subclass-of;
$tag-class-141 value "NascarDriver", isa tag-class, id "tag-class-141";
$tag-class-141_name_999736348 isa name, value "NascarDriver";
(entity-value $tag-class-141_name_999736348, entity-target $tag-class-141), isa entity-has-resource;
$tag-class-149 id "tag-class-149", isa tag-class;
(superclass $tag-class-149, subclass $tag-class-141), isa subclass-of;
$tag-class-310 id "tag-class-310", value "BaseballPlayer", isa tag-class;
$tag-class-310_name_850006897 isa name, value "BaseballPlayer";
(entity-value $tag-class-310_name_850006897, entity-target $tag-class-310), isa entity-has-resource;
$tag-class-149 id "tag-class-149", isa tag-class;
(superclass $tag-class-149, subclass $tag-class-310), isa subclass-of;
$tag-class-332 id "tag-class-332", value "ChristianBishop", isa tag-class;
$tag-class-332_name_-1766959754 isa name, value "ChristianBishop";
(entity-value $tag-class-332_name_-1766959754, entity-target $tag-class-332), isa entity-has-resource;
$tag-class-109 id "tag-class-109", isa tag-class;
(superclass $tag-class-109, subclass $tag-class-332), isa subclass-of;
$tag-class-355 id "tag-class-355", value "Chancellor", isa tag-class;
$tag-class-355_name_-252251977 isa name, value "Chancellor";
isa entity-has-resource, (entity-target $tag-class-355, entity-value $tag-class-355_name_-252251977);
$tag-class-95 isa tag-class, id "tag-class-95";
(subclass $tag-class-355, superclass $tag-class-95), isa subclass-of;
$tag-class-219 id "tag-class-219", isa tag-class, value "Senator";
$tag-class-219_name_-650469486 isa name, value "Senator";
isa entity-has-resource, (entity-value $tag-class-219_name_-650469486, entity-target $tag-class-219);
$tag-class-95 isa tag-class, id "tag-class-95";
(superclass $tag-class-95, subclass $tag-class-219), isa subclass-of;
$tag-class-61 value "Band", isa tag-class, id "tag-class-61";
$tag-class-61_name_2062933 isa name, value "Band";
(entity-value $tag-class-61_name_2062933, entity-target $tag-class-61), isa entity-has-resource;
$tag-class-301 id "tag-class-301", isa tag-class;
(superclass $tag-class-301, subclass $tag-class-61), isa subclass-of;
$tag-class-301 value "Organisation", id "tag-class-301", isa tag-class;
$tag-class-301_name_1142838522 isa name, value "Organisation";
(entity-value $tag-class-301_name_1142838522, entity-target $tag-class-301), isa entity-has-resource;
$tag-class-239 isa tag-class, id "tag-class-239";
(subclass $tag-class-301, superclass $tag-class-239), isa subclass-of;
$tag-class-72 value "Boxer", isa tag-class, id "tag-class-72";
$tag-class-72_name_64377752 isa name, value "Boxer";
(entity-value $tag-class-72_name_64377752, entity-target $tag-class-72), isa entity-has-resource;
$tag-class-149 id "tag-class-149", isa tag-class;
(superclass $tag-class-149, subclass $tag-class-72), isa subclass-of;
$tag-class-104 value "AmericanFootballPlayer", id "tag-class-104", isa tag-class;
$tag-class-104_name_-1009987314 isa name, value "AmericanFootballPlayer";
(entity-value $tag-class-104_name_-1009987314, entity-target $tag-class-104), isa entity-has-resource;
$tag-class-47 id "tag-class-47", isa tag-class;
(subclass $tag-class-104, superclass $tag-class-47), isa subclass-of;
$tag-class-47 id "tag-class-47", isa tag-class, value "GridironFootballPlayer";
$tag-class-47_name_-1726996100 isa name, value "GridironFootballPlayer";
isa entity-has-resource, (entity-target $tag-class-47, entity-value $tag-class-47_name_-1726996100);
$tag-class-149 id "tag-class-149", isa tag-class;
(subclass $tag-class-47, superclass $tag-class-149), isa subclass-of;
$tag-class-152 value "SnookerChamp", isa tag-class, id "tag-class-152";
$tag-class-152_name_-1094837662 isa name, value "SnookerChamp";
isa entity-has-resource, (entity-value $tag-class-152_name_-1094837662, entity-target $tag-class-152);
$tag-class-112 id "tag-class-112", isa tag-class;
(superclass $tag-class-112, subclass $tag-class-152), isa subclass-of;
$tag-class-112 id "tag-class-112", value "SnookerPlayer", isa tag-class;
$tag-class-112_name_795655198 isa name, value "SnookerPlayer";
isa entity-has-resource, (entity-target $tag-class-112, entity-value $tag-class-112_name_795655198);
$tag-class-149 id "tag-class-149", isa tag-class;
isa subclass-of, (subclass $tag-class-112, superclass $tag-class-149);
$tag-class-347 id "tag-class-347", value "Governor", isa tag-class;
$tag-class-347_name_-1905803434 isa name, value "Governor";
(entity-value $tag-class-347_name_-1905803434, entity-target $tag-class-347), isa entity-has-resource;
$tag-class-95 isa tag-class, id "tag-class-95";
(superclass $tag-class-95, subclass $tag-class-347), isa subclass-of;
$tag-class-173 value "Model", isa tag-class, id "tag-class-173";
$tag-class-173_name_74517257 isa name, value "Model";
isa entity-has-resource, (entity-target $tag-class-173, entity-value $tag-class-173_name_74517257);
$tag-class-211 id "tag-class-211", isa tag-class;
(subclass $tag-class-173, superclass $tag-class-211), isa subclass-of;
$tag-class-295 value "FictionalCharacter", isa tag-class, id "tag-class-295";
$tag-class-295_name_1943189450 isa name, value "FictionalCharacter";
(entity-value $tag-class-295_name_1943189450, entity-target $tag-class-295), isa entity-has-resource;
$tag-class-211 id "tag-class-211", isa tag-class;
(subclass $tag-class-295, superclass $tag-class-211), isa subclass-of;
$tag-class-287 id "tag-class-287", value "Criminal", isa tag-class;
$tag-class-287_name_2010341507 isa name, value "Criminal";
isa entity-has-resource, (entity-value $tag-class-287_name_2010341507, entity-target $tag-class-287);
$tag-class-211 id "tag-class-211", isa tag-class;
(subclass $tag-class-287, superclass $tag-class-211), isa subclass-of;
$tag-class-167 id "tag-class-167", value "Congressman", isa tag-class;
$tag-class-167_name_-1507989054 isa name, value "Congressman";
isa entity-has-resource, (entity-target $tag-class-167, entity-value $tag-class-167_name_-1507989054);
$tag-class-95 isa tag-class, id "tag-class-95";
(superclass $tag-class-95, subclass $tag-class-167), isa subclass-of;
$tag-class-145 value "Film", id "tag-class-145", isa tag-class;
$tag-class-145_name_2189732 isa name, value "Film";
(entity-value $tag-class-145_name_2189732, entity-target $tag-class-145), isa entity-has-resource;
$tag-class-188 id "tag-class-188", isa tag-class;
(superclass $tag-class-188, subclass $tag-class-145), isa subclass-of;
$tag-class-188 id "tag-class-188", value "Work", isa tag-class;
$tag-class-188_name_2702129 isa name, value "Work";
isa entity-has-resource, (entity-value $tag-class-188_name_2702129, entity-target $tag-class-188);
$tag-class-0 isa tag-class, id "tag-class-0";
(superclass $tag-class-0, subclass $tag-class-188), isa subclass-of;
$tag-class-339 value "Astronaut", isa tag-class, id "tag-class-339";
$tag-class-339_name_280122417 isa name, value "Astronaut";
isa entity-has-resource, (entity-value $tag-class-339_name_280122417, entity-target $tag-class-339);
$tag-class-211 id "tag-class-211", isa tag-class;
isa subclass-of, (superclass $tag-class-211, subclass $tag-class-339);
$tag-class-77 id "tag-class-77", value "CollegeCoach", isa tag-class;
$tag-class-77_name_590900579 isa name, value "CollegeCoach";
isa entity-has-resource, (entity-value $tag-class-77_name_590900579, entity-target $tag-class-77);
$tag-class-211 id "tag-class-211", isa tag-class;
isa subclass-of, (subclass $tag-class-77, superclass $tag-class-211);
$tag-class-46 value "AdultActor", id "tag-class-46", isa tag-class;
$tag-class-46_name_-2044692357 isa name, value "AdultActor";
isa entity-has-resource, (entity-value $tag-class-46_name_-2044692357, entity-target $tag-class-46);
$tag-class-200 id "tag-class-200", isa tag-class;
(superclass $tag-class-200, subclass $tag-class-46), isa subclass-of;
$tag-class-342 value "Single", id "tag-class-342", isa tag-class;
$tag-class-342_name_-1818398616 isa name, value "Single";
isa entity-has-resource, (entity-target $tag-class-342, entity-value $tag-class-342_name_-1818398616);
$tag-class-123 id "tag-class-123", isa tag-class;
(subclass $tag-class-342, superclass $tag-class-123), isa subclass-of;
$tag-class-123 id "tag-class-123", value "MusicalWork", isa tag-class;
$tag-class-123_name_-987897823 isa name, value "MusicalWork";
isa entity-has-resource, (entity-value $tag-class-123_name_-987897823, entity-target $tag-class-123);
$tag-class-188 id "tag-class-188", isa tag-class;
isa subclass-of, (subclass $tag-class-123, superclass $tag-class-188);
$tag-class-182 value "Album", id "tag-class-182", isa tag-class;
$tag-class-182_name_63344207 isa name, value "Album";
isa entity-has-resource, (entity-value $tag-class-182_name_63344207, entity-target $tag-class-182);
$tag-class-123 id "tag-class-123", isa tag-class;
isa subclass-of, (superclass $tag-class-123, subclass $tag-class-182);
$tag-class-180 isa tag-class, id "tag-class-180", value "Song";
$tag-class-180_name_2582837 isa name, value "Song";
isa entity-has-resource, (entity-target $tag-class-180, entity-value $tag-class-180_name_2582837);
$tag-class-123 id "tag-class-123", isa tag-class;
(superclass $tag-class-123, subclass $tag-class-180), isa subclass-of;
$tag-class-62 isa tag-class, id "tag-class-62", value "Country";
$tag-class-62_name_-1672482954 isa name, value "Country";
(entity-target $tag-class-62, entity-value $tag-class-62_name_-1672482954), isa entity-has-resource;
$tag-class-318 id "tag-class-318", isa tag-class;
(subclass $tag-class-62, superclass $tag-class-318), isa subclass-of;
$tag-class-318 value "PopulatedPlace", id "tag-class-318", isa tag-class;
$tag-class-318_name_1197663373 isa name, value "PopulatedPlace";
(entity-target $tag-class-318, entity-value $tag-class-318_name_1197663373), isa entity-has-resource;
$tag-class-303 id "tag-class-303", isa tag-class;
(superclass $tag-class-303, subclass $tag-class-318), isa subclass-of;
$tag-class-303 value "Place", id "tag-class-303", isa tag-class;
$tag-class-303_name_77195495 isa name, value "Place";
(entity-value $tag-class-303_name_77195495, entity-target $tag-class-303), isa entity-has-resource;
$tag-class-0 isa tag-class, id "tag-class-0";
isa subclass-of, (superclass $tag-class-0, subclass $tag-class-303);
$tag-class-302 value "ComicsCharacter", id "tag-class-302", isa tag-class;
$tag-class-302_name_1331339377 isa name, value "ComicsCharacter";
(entity-target $tag-class-302, entity-value $tag-class-302_name_1331339377), isa entity-has-resource;
$tag-class-295 isa tag-class, id "tag-class-295";
(subclass $tag-class-302, superclass $tag-class-295), isa subclass-of;
$tag-class-233 id "tag-class-233", isa tag-class, value "EurovisionSongContestEntry";
$tag-class-233_name_636402888 isa name, value "EurovisionSongContestEntry";
isa entity-has-resource, (entity-target $tag-class-233, entity-value $tag-class-233_name_636402888);
$tag-class-180 isa tag-class, id "tag-class-180";
(subclass $tag-class-233, superclass $tag-class-180), isa subclass-of;
$tag-class-41 value "Company", isa tag-class, id "tag-class-41";
$tag-class-41_name_-1679829923 isa name, value "Company";
(entity-value $tag-class-41_name_-1679829923, entity-target $tag-class-41), isa entity-has-resource;
$tag-class-301 id "tag-class-301", isa tag-class;
(superclass $tag-class-301, subclass $tag-class-41), isa subclass-of;
$tag-class-243 id "tag-class-243", value "MilitaryUnit", isa tag-class;
$tag-class-243_name_669513809 isa name, value "MilitaryUnit";
isa entity-has-resource, (entity-target $tag-class-243, entity-value $tag-class-243_name_669513809);
$tag-class-301 id "tag-class-301", isa tag-class;
(subclass $tag-class-243, superclass $tag-class-301), isa subclass-of;
$tag-class-242 id "tag-class-242", value "SportsTeamMember", isa tag-class;
$tag-class-242_name_161584214 isa name, value "SportsTeamMember";
(entity-target $tag-class-242, entity-value $tag-class-242_name_161584214), isa entity-has-resource;
$tag-class-67 id "tag-class-67", isa tag-class;
(subclass $tag-class-242, superclass $tag-class-67), isa subclass-of;
$tag-class-67 id "tag-class-67", isa tag-class, value "OrganisationMember";
$tag-class-67_name_-217274316 isa name, value "OrganisationMember";
(entity-target $tag-class-67, entity-value $tag-class-67_name_-217274316), isa entity-has-resource;
$tag-class-211 id "tag-class-211", isa tag-class;
(subclass $tag-class-67, superclass $tag-class-211), isa subclass-of;
