insert

original-post sub relation
  relates reply
  relates original;

post plays reply;
comment plays contained;

$originalPostOfPosts isa inference-rule
lhs {
  $p isa post;
}
rhs {
  (reply: $p, original: $p) isa original-post;
};

$originalPostOfComments isa inference-rule
lhs {
  (reply: $c, original: $m) isa reply-of;
  (reply: $m, original: $op) isa original-post;
}
rhs {
  (reply: $c, original: $op) isa original-post;
};

$forumOfComments isa inference-rule
lhs {
  $m isa comment;
  (reply: $m, original: $op) isa original-post;
  (contained: $op, container: $forum) isa container-of;
}
rhs {
  (contained: $m, container: $forum) isa container-of;
};
