# The relationships defined in the ldbc-snb benchmark
insert

"contained" sub role;
"container" sub role;
"container-of" sub relation
	has-role contained
	has-role container;

"creator" sub role;
"product" sub role;
"has-creator" sub relation
	has-role creator
	has-role product;

"interest" sub role;
"interested" sub role;
"has-interest" sub relation
	has-role interest
	has-role interested;

"member" sub role;
"group" sub role;
"has-member" sub relation
	has-resource join-date
	has-role member
	has-role group;

"moderator" sub role;
"moderated" sub role;
"has-moderator" sub relation
	has-role moderator
	has-role moderated;

"tagged" sub role;
"label" sub role;
"has-tag" sub relation
	has-role tagged
	has-role label;

"class" sub role;
"instance" sub role;
"has-type" sub relation
	has-role class
	has-role instance;

"part" sub role;
"whole" sub role;
"is-part-of" sub relation
	has-role part
	has-role whole;

"located" sub role;
"region" sub role;
"is-located-in" sub relation
	has-role located
	has-role region;

"subclass" sub role;
"superclass" sub role;
"is-subclass-of" sub relation
	has-role subclass
	has-role superclass;

"friend" sub role;
"knows" sub relation
	has-resource creation-date
	has-role friend;

"like" sub role;
"admirer" sub role;
"likes" sub relation
	has-resource creation-date
	has-role like
	has-role admirer;

"reply" sub role;
"original" sub role;
"reply-of" sub relation
	has-role reply
	has-role original;

"school" sub role;
"student" sub role;
"study-at" sub relation
	has-resource class-year
	has-role school
	has-role student;

"employee" sub role;
"employer" sub role;
"work-at" sub relation
	has-resource work-from
	has-role employer,
	has-role employee;	
