# The entities defined in the ldbc-snb benchmark
insert

# geographic entities
"place" sub entity
	has-key place-id
	has-resource name
	has-resource url
	plays region;

"city" sub place
	plays part;

"country" sub place
	plays whole
	plays part;

"continent" sub place
	plays whole;

# message board entities
"forum" sub entity
	has-key forum-id
	has-resource title
	has-resource creation-date
	plays container
	plays group
	plays moderated
	plays tagged;

"message" sub entity
	is-abstract
	has-key message-id
	has-resource browser-used
	has-resource creation-date
	has-resource location-ip
	has-resource content
	has-resource length
	plays product
	plays tagged
	plays located
	plays like
	plays original;

"comment" sub message
	plays reply;

"post" sub message
	has-resource language
	has-resource image-file
	plays contained;

"tag" sub entity
	has-key tag-id
	has-resource name
	has-resource url
	plays interest
	plays topic
	plays instance;

"tag-class" sub entity
	has-key tag-class-id
	has-resource name
	has-resource url
	plays class
	plays subclass
	plays superclass;

# institutional entities
"organisation" sub entity
	has-key organisation-id
	has-resource name
	has-resource url
	plays located;

"company" sub organisation
	plays employer;

"university" sub organisation
	plays school;

# individuals
"person" sub entity
	has-key person-id
	has-resource first-name
	has-resource last-name
	has-resource gender
	has-resource birth-day
	has-resource email
	has-resource speaks
	has-resource browser-used
	has-resource location-ip
	has-resource creation-date
	plays creator
	plays interested
	plays member
	plays moderator
	plays located
	plays friend
	plays admirer
	plays employee
	plays student;