insert $x isa post
	has message-id @long(<id>)
	has image-file <imageFile>
	has creation-date <creationDate>
	has location-ip <locationIP>
	has browser-used <browserUsed>
	has language <language>
	has content <content>
	has length @long(<length>);