match
	$person isa person, has person-id @long(<Person.id>);
	$person1 isa person, has person-id @long(<Person1.id>);
insert
	(contact-1: $person, contact-2: $person1) isa knows
	has creation-date <creationDate>;