insert $x isa person
	has person-id @long(<id>)
	has first-name <firstName>
	has last-name <lastName>
	has gender <gender>
	has birth-day <birthday>
	has creation-date <creationDate>
	has location-ip <locationIP>
	has browser-used <browserUsed>;