match
	$person isa person, has person-id @long(<Person.id>);
	$organisation isa organization, has organization-id @long(<Organisation.id>);
insert
	(institution: $organisation, individual: $person) isa work-at
	has work-from @long(<workFrom>);