match
	$person isa person, has person-id @long(<Person.id>);
	$organisation isa organization, has organization-id @long(<Organisation.id>);
insert
	(institution: $organisation, individual: $person) isa study-at
	has class-year @long(<classYear>);
